sudo: false
language: node_js
node_js:
  - '4'
env:
  global:
    - secure: bVBXJ4aKep5PzZG+FxNi75BylO5wb9dWHPM+PeKLmQ0tqdfUyBmnk/XRC1QxHO9v6xg1AmCGjiZCEvjwZ53g3Y4xWD2GcqAvjDjHGGq2OOygqDgNsqkY9MkRR2JXldyFIrUzo6rZKli9IKyU101Ga0UIhxEt77y4jMM3YEXbhNO/G9NfJQfKeb+VaotQ3vyugLCLqvFESyAIifiif7CqnzvGCt4TEOmbLxrmzatGy+ZRe57miZbmi1714QGb6AXFlyNTS+l6tA2/wkZsefdD1TZtVAZ7++6T3wxYDl8IBa1No6j3AbBDtVHpBFXEAnRvcn7NYgsFV0Oiak3ACVm9y0vLV6RThJrZH2DiAuUCbqy3FImICcW9Bbh5j37CcsRqXwbGiD7UComBUEPpKK8ssl27X/meEF6gSZ+MMlWxASCTT8DLjkgI1aCccXc1FxCFzaIGRsrh/tTd2YDh3WwVvGRVCSDZzfiGgBIfjZgrIPcvJ4mF9kLJR6ekmE9icY6bZaQT0NIwNubXMASduqRP4vT74CSKMBqmLbIb7oFxWbaxs/ZJYfNYdykjxBcOdMmiRbouunfEVXyKd+S+tK/vgnkkQo1wkT4mgFFE/c9plDaZcCJN19A+tyAHWHGevrRt3DC6dXfpqxrhEq3lyF8nDTIWj8G4yRwjJrNUDGAvrtc=
